FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Directory.Build.props", "./"]
COPY ["source/API/Evently.Api/Evently.Api.csproj", "source/API/Evently.Api/"]
COPY ["source/Modules/Events/Evently.Modules.Events.Api/Evently.Modules.Events.Api.csproj", "source/Modules/Events/Evently.Modules.Events.Api/"]
RUN dotnet restore "source/API/Evently.Api/Evently.Api.csproj"
COPY . .
WORKDIR "/src/source/API/Evently.Api"
RUN dotnet build "Evently.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Evently.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Evently.Api.dll"]
